version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "software.amazon.awssdk:*" # reduce the noise of frequent AWS SDK updates
        update-types: ["version-update:semver-patch"]
      - dependency-name: "com.amazonaws:*" # reduce the noise of frequent AWS SDK updates
        update-types: ["version-update:semver-patch"]
