version: "3"
services:
  prison-to-probation-update:
    image: quay.io/hmpps/prison-to-probation-update:latest
    network_mode: "host"
    container_name: prison-to-probation-update
    depends_on:
      - localstack
      - prison-api
      - community-api
    ports:
      - "8084:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - COMMUNITY_ENDPOINT_URL=http://localhost:8096
      - OAUTH_API_BASE_URL=http://localhost:8090/auth
      - PRISON_ENDPOINT_URL=http://localhost:8093
      - SQS_ENDPOINT_URL=http://localhost:4566
      - SPRING_PROFILES_ACTIVE=stdout,localstack
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - AWS_DEFAULT_REGION=eu-west-2
      - OAUTH_CLIENT_SECRET=clientsecret
      - OAUTH_CLIENT_ID=prison-to-probation-update-api-client

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    container_name: prison-api
    depends_on:
      - oauth
    ports:
      - "8093:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: oauth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  community-api:
    image: quay.io/hmpps/community-api:latest
    networks:
      - hmpps
    container_name: community-api
    ports:
      - "8096:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  offender-search:
    image: quay.io/hmpps/offender-search:latest
    networks:
      - hmpps
    container_name: offender-search
    ports:
      - "8097:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=localstack,dev
  localstack:
    image: localstack/localstack
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - 8999:8080
    environment:
      - SERVICES=sns,sqs,es,dynamodb
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
