graceful:
  shutdown.enabled: false

hmpps.sqs:
  queues:
    prisoneventqueue:
      queueName: dps-queue
      dlqName: dps-dlq
    hmppseventqueue:
      queueName: hmpps-queue
      dlqName: hmpps-dlq

hmpps.sns:
  topics:
    prisonEventTopic:
      topicArn: arn:aws:sns:eu-west-2:000000000000:offender_events
    hmppsEventTopic:
      topicArn: arn:aws:sns:eu-west-2:000000000000:hmpps-event-topic

hmpps.dynamodb:
  provider: ${aws.provider}
  localstackUrl: http://localhost:4566
  tableName: main-table
  scheduleTableName: schedule-table

oauth:
  endpoint.url: http://localhost:8090/auth

prison:
  endpoint.url: http://localhost:8093

community:
  endpoint.url: http://localhost:8096

offender-search:
  endpoint.url: http://localhost:8097

aws:
  provider: localstack
