graceful:
  shutdown.enabled: false

hmpps.sqs:
  provider: ${aws.provider}
  sqsUrl: http://localhost:4566
  snsUrl: http://localhost:4566
  dpsQueue:
    topicName: ${random.uuid}
    queueName: ${random.uuid}
    dlqName: ${random.uuid}
  hmppsQueue:
    topicName: ${random.uuid}
    queueName: ${random.uuid}
    dlqName: ${random.uuid}

oauth:
  endpoint.url: http://localhost:8090/auth

prison:
  endpoint.url: http://localhost:8093

community:
  endpoint.url: http://localhost:8096

offender-search:
  endpoint.url: http://localhost:8097

hmpps.dynamodb:
  provider: ${aws.provider}
  localstackUrl: http://localhost:4566
  tableName: ${random.uuid}
  scheduleTableName: ${random.uuid}

aws:
  provider: localstack
