graceful:
  shutdown.enabled: false

sqs:
  endpoint.url: http://localhost:4576

oauth:
  endpoint.url: http://localhost:8090/auth

elite2:
  endpoint.url: http://localhost:8093

community:
  endpoint.url: http://localhost:8096

offender-search:
  endpoint.url: http://localhost:8097

dynamodb:
  endpoint: http://localhost:4569
  tableName: cp-message
  schedule:
    tableName: cp-schedule

aws:
  provider: localstack