graceful:
  shutdown.enabled: false

sqs:
  endpoint.url: http://localhost:4576
  provider: localstack

oauth:
  endpoint.url: http://localhost:8090/auth

elite2:
  endpoint.url: http://localhost:8093

community:
  endpoint.url: http://localhost:8096

offender-search:
  endpoint.url: http://localhost:8097
