graceful:
  shutdown.enabled: false

hmpps.sqs:
  provider: localstack
  queues:
    prisoneventqueue:
      queueName: dps-queue
      dlqName: dps-dlq
      subscribeTopicId: prisoneventtopic
      subscribeFilter: '{"eventType":[ "PRISONER_RELEASED", "PRISONER_RECEIVED"] }'
  topics:
    prisoneventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:offender_events
    domaineventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:domain_events

hmpps.dynamodb:
  provider: ${aws.provider}
  localstackUrl: http://localhost:4566
  tableName: main-table
  scheduleTableName: schedule-table

oauth:
  endpoint.url: http://localhost:8090/auth

prison:
  endpoint.url: http://localhost:8093

community:
  endpoint.url: http://localhost:8096

offender-search:
  endpoint.url: http://localhost:8097

aws:
  provider: localstack
