graceful:
  shutdown.enabled: false

hmpps.sqs:
  sqsUrl: http://localhost:4566
  snsUrl: http://localhost:4566
  dpsQueue:
    topicName: ${random.uuid}
    queueName: ${random.uuid}
    dlqName: ${random.uuid}
  hmppsQueue:
    topicName: ${random.uuid}
    queueName: ${random.uuid}
    dlqName: ${random.uuid}

oauth:
  endpoint.url: http://localhost:8090/auth

prison:
  endpoint.url: http://localhost:8093

community:
  endpoint.url: http://localhost:8096

offender-search:
  endpoint.url: http://localhost:8097

dynamodb:
  endpoint: http://localhost:4566
  tableName: cp-message
  schedule:
    tableName: cp-schedule

aws:
  provider: localstack
