graceful:
  shutdown.enabled: false

hmpps.sqs:
  provider: ${aws.provider}
  localstackUrl: http://localhost:4566
  queues:
    prisonEventQueue:
      topicName: dps-topic
      queueName: dps-queue
      dlqName: dps-dlq
    hmppsDomainEventQueue:
      topicName: hmpps-topic
      queueName: hmpps-queue
      dlqName: hmpps-dlq

hmpps.dynamodb:
  provider: ${aws.provider}
  localstackUrl: http://localhost:4566
  tableName: main-table
  scheduleTableName: schedule-table

oauth:
  endpoint.url: http://localhost:8090/auth

prison:
  endpoint.url: http://localhost:8093

community:
  endpoint.url: http://localhost:8096

offender-search:
  endpoint.url: http://localhost:8097

aws:
  provider: localstack
