version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.14

jobs:
  validate:
    executor:
      name: hmpps/java
      tag: "17.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle.kts
  test-integration:
    executor:
      name: hmpps/localstack
      jdk_tag: "17.0"
      services: "sqs,sns,dynamodb"
      localstack_tag: "0.12.10"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - run:
          name: Wait for Localstack to be ready
          command: curl -4 --connect-timeout 30 --retry-connrefused --retry 20 --retry-delay 5 http://localhost:4566
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew testIntegration
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - test-integration:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          jira_update: true
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - test-integration
            - helm_lint
            - build_docker
      - hmpps/smoke_test:
          context: hmpps-smoketest-common-vars
          name: smoke_test
          jdk_tag: "17.0"
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          jira_env_type: staging
          context:
            - prison-to-probation-update-preprod
            - hmpps-common-vars
          requires:
            - smoke_test
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          jira_env_type: production
          slack_notification: true
          slack_channel_name: probation-integration-notifications
          context:
            - prison-to-probation-update-prod
            - hmpps-common-vars
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "2 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          cache_key: v2_0
          cache_key: v2_0
          slack_channel: probation-integration-notifications
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: probation-integration-notifications
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: probation-integration-notifications
          context:
            - hmpps-common-vars
            - veracode-credentials
  security-weekly:
    triggers:
      - schedule:
          cron: "40 6 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: probation-integration-notifications
          context:
            - veracode-credentials
            - hmpps-common-vars

