---
# Environment specific values, override helm_deploy/prison-to-probation-update/values.yaml
generic-service:
  ingress:
    host: "prison-to-probation-update-preprod.prison.service.justice.gov.uk"
  env:
    JWT_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBalRkdXRLS2VQUkJlQWNrZ1M2cC8NCmxWK2Q1WXFiM3ExOHo2VXdoMU1OWXhwM0hxWXBZVis5MnlGeGUyUTVSN0tWakl5S3kyZkdBanNXeStlU04yM1QNCkZURVVUeXdHdnc0SkJrRGRoaUUvKy80SjR2TWFHMzBYN29GdE9JUWIwaENFQVlWM3o4emc1WVd2OGZlRkVnWGcNCkp3SjVCc2krU0NvajNIZDlERXk1ZGZaTTljL3BoOXN5YWpLU1ZiQW8rRCtXanhQWHU4UndRSk9BU0g0NUVwclQNCjNJMy9NdllyY1ZvdkN4UVZyUWNwYzNiY0U0bHpYdFlSVy9wSWpHUVpBKy9WYjNXZXZuR1FiYndTNHp6eXkzazgNCkRCZ0pzQVJlVDI1eHp0ckptRGlZZXBHYkVKVHV0alRqR2NVOG1qUjRWZ3gwdHdqMk9DMzBES3dXbGlrMzhXTWwNCk5RSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0="
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://api-preprod.prison.service.justice.gov.uk"
    COMMUNITY_ENDPOINT_URL: "https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io"
    OFFENDER_SEARCH_ENDPOINT_URL: "https://probation-offender-search-preprod.hmpps.service.justice.gov.uk"
    PRISONTOPROBATION_ONLY_PRISONS: ""
    RETRY_SCHEDULES_SHORT_CRON: "0 0 * * * *"
    RETRY_SCHEDULES_MEDIUM_CRON: "0 15 */4 * * *"
    RETRY_SCHEDULES_LONG_CRON: "0 30 23 * * *"
    PRISONTOPROBATION_MESSAGE_PROCESSOR_DELAY: 10000
    PRISONTOPROBATION_HOLD_BACK_DURATION: "60m"
