---
# Environment specific values, override helm_deploy/prison-to-probation-update/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: "prison-to-probation-update-dev.prison.service.justice.gov.uk"
    contextColour: green
  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://api-dev.prison.service.justice.gov.uk"
    COMMUNITY_ENDPOINT_URL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
    OFFENDER_SEARCH_ENDPOINT_URL: "https://probation-offender-search-dev.hmpps.service.justice.gov.uk"
    PRISONTOPROBATION_ONLY_PRISONS: ""
    RETRY_SCHEDULES_SHORT_CRON: "0 * * * * *"
    RETRY_SCHEDULES_MEDIUM_CRON: "15 */2 * * * *"
    RETRY_SCHEDULES_LONG_CRON: "30 */4 * * * *"
    PRISONTOPROBATION_MESSAGE_PROCESSOR_DELAY: 1000
    # small delay to aid testing
    PRISONTOPROBATION_HOLD_BACK_DURATION: "1m"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications

  # Alert for business hours only - 7am to 6pm UTC (8am to 7pm BST) on week days (Monday to Friday)
  businessHoursOnly: true
