---
# Environment specific values, override helm_deploy/prison-to-probation-update/values.yaml
generic-service:
  ingress:
    host: "prison-to-probation-update.prison.service.justice.gov.uk"
    contextColour: green
  env:
    OAUTH_ENDPOINT_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://api.prison.service.justice.gov.uk"
    COMMUNITY_ENDPOINT_URL: "https://community-api-secure.probation.service.justice.gov.uk"
    OFFENDER_SEARCH_ENDPOINT_URL: "https://probation-offender-search.hmpps.service.justice.gov.uk"
    PRISONTOPROBATION_ONLY_PRISONS: ""
    RETRY_SCHEDULES_SHORT_CRON: "0 0 * * * *"
    RETRY_SCHEDULES_MEDIUM_CRON: "0 15 */4 * * *"
    RETRY_SCHEDULES_LONG_CRON: "0 30 23 * * *"
    PRISONTOPROBATION_MESSAGE_PROCESSOR_DELAY: 10000
    PRISONTOPROBATION_HOLD_BACK_DURATION: "60m"

# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: probation-integration-notifications
