---
# Environment specific values, override helm_deploy/prison-to-probation-update/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: "prison-to-probation-update-dev.prison.service.justice.gov.uk"
  env:
    JWT_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6Y3g3WWJ3MkJBV3Y3U3NFSVVHUAppeUpTSURndHFCeDE5VHdtN3VJM1RYNXpSY3JabFV4Y0VtUEpHVWd5K0QySkloVmxxbWVxd0dWMkNOT3FaQmdHCmo4ZUpHQTU5aUlUemU4ZG1SSk5JYzdsNmxESmc5RE5KVk9pTHFVbFpGRENJcXplSTYzb3E2dWhjY2c1RFBpVE4KcU9HWmM4dXBOK3c1ZFpyTnYrMkdMZ3hLMnBldE1VL0JoWWVXZjNLdllJTzE2djF1dm5GT0dPMTNIb1d1NUJ0ZApTdC9UZ2NsRmhWTEVkR3c3WGJpWUhuTlpJZGh3YU5RaVlnbVhtalpWZE15Q1BETW8xMExrVjFwM1V5MTVwTU14ClVwc2xKYU8wNlZIYXJtY3ZWYzNleHg5NlpHTjE2T2U4ZWZoeG5Rdmhzd0ZrbXlYT25sSForNDI1MnJHcHlKTG8KbHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
    OAUTH_ENDPOINT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    PRISON_ENDPOINT_URL: "https://api-dev.prison.service.justice.gov.uk"
    COMMUNITY_ENDPOINT_URL: "https://community-api-secure.test.delius.probation.hmpps.dsd.io"
    OFFENDER_SEARCH_ENDPOINT_URL: "https://probation-offender-search-dev.hmpps.service.justice.gov.uk"
    PRISONTOPROBATION_ONLY_PRISONS: ""
    RETRY_SCHEDULES_SHORT_CRON: "0 * * * * *"
    RETRY_SCHEDULES_MEDIUM_CRON: "15 */2 * * * *"
    RETRY_SCHEDULES_LONG_CRON: "30 */4 * * * *"
    PRISONTOPROBATION_MESSAGE_PROCESSOR_DELAY: 1000
    # small delay to aid testing
    PRISONTOPROBATION_HOLD_BACK_DURATION: "1m"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
