---
# Values here are the same across all environments
generic-service:
  nameOverride: prison-to-probation-update
  serviceAccountName: prison-to-probation-update
  resources:
    requests:
      cpu: 1
      memory: 512Mi

  image:
    repository: quay.io/hmpps/prison-to-probation-update
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /prometheus {
          deny all;
          return 401;
        }
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
    tlsSecretName: prison-to-probation-update-cert

  env:
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    JDK_JAVA_OPTIONS: "-javaagent:/agent/agent.jar -XX:MaxRAMPercentage=75.0"

  namespace_secrets:
    prison-to-probation-update:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "PRISON_TO_PROBATION_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "PRISON_TO_PROBATION_CLIENT_SECRET"
    prison-to-probation-update-queue:
      HMPPS_SQS_QUEUES_PRISONEVENTQUEUE_QUEUE_NAME: "QUEUE_NAME"
    prison-to-probation-update-dlq:
      HMPPS_SQS_QUEUES_PRISONEVENTQUEUE_DLQ_NAME: "QUEUE_NAME"
    message-dynamodb-output:
      DYNAMODB_TABLENAME: "table_name"
      DYNAMODB_AWS_ACCESS_KEY_ID: "access_key_id"
      DYNAMODB_AWS_SECRET_ACCESS_KEY: "secret_access_key"
    schedule-dynamodb-output:
      DYNAMODB_SCHEDULE_TABLENAME: "table_name"
      DYNAMODB_SCHEDULE_AWS_ACCESS_KEY_ID: "access_key_id"
      DYNAMODB_SCHEDULE_AWS_SECRET_ACCESS_KEY: "secret_access_key"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: prison-to-probation-update
