---
# Values here are the same across all environments
generic-service:
  nameOverride: prison-to-probation-update

  image:
    repository: quay.io/hmpps/prison-to-probation-update
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/custom-http-errors: "418"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        server_tokens off;
        location /prometheus {
          deny all;
          return 401;
        }
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
    tlsSecretName: prison-to-probation-update-cert
    path: /

  env:
    SERVER_PORT: "8080"
    JAVA_OPTS: "-Xmx512m"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    prison-to-probation-update:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "PRISON_TO_PROBATION_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "PRISON_TO_PROBATION_CLIENT_SECRET"
    ptpu-sqs-instance-output:
      SQS_AWS_ACCESS_KEY_ID: "access_key_id"
      SQS_AWS_SECRET_ACCESS_KEY: "secret_access_key"
      SQS_QUEUE_NAME: "sqs_ptpu_name"
    ptpu-sqs-dl-instance-output:
      SQS_AWS_DLQ_ACCESS_KEY_ID: "access_key_id"
      SQS_AWS_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      SQS_DLQ_NAME: "sqs_ptpu_name"
    sqs-hmpps-domain-events:
      SQS_HMPPS_AWS_ACCESS_KEY_ID: "access_key_id"
      SQS_HMPPS_AWS_SECRET_ACCESS_KEY: "secret_access_key"
      SQS_HMPPS_QUEUE_NAME: "sqs_queue_name"
    sqs-hmpps-domain-events-dlq:
      SQS_HMPPS_AWS_DLQ_ACCESS_KEY_ID: "access_key_id"
      SQS_HMPPS_AWS_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
      SQS_HMPPS_DLQ_NAME: "sqs_queue_name"
    message-dynamodb-output:
      DYNAMODB_TABLENAME: "table_name"
      DYNAMODB_AWS_ACCESS_KEY_ID: "access_key_id"
      DYNAMODB_AWS_SECRET_ACCESS_KEY: "secret_access_key"
    schedule-dynamodb-output:
      DYNAMODB_SCHEDULE_TABLENAME: "table_name"
      DYNAMODB_SCHEDULE_AWS_ACCESS_KEY_ID: "access_key_id"
      DYNAMODB_SCHEDULE_AWS_SECRET_ACCESS_KEY: "secret_access_key"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: prison-to-probation-update
